[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "goombay"
version = "0.24.9"
authors = [{ name = "Andrew Hennis", email = "andrew.mr.hennis@gmail.com" }]
description = "Python implementation of several sequence alignment algorithms such as Needleman-Wunsch, Waterman-Smith-Beyer, and Gotoh intended to calculate distance, show alignment, and display the underlying matrices."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
 "biobase>=0.8.0",
 "biopython>=1.85",
 "numpy>=2.2.6",
]

[project.optional-dependencies]
dev = ["pytest", "black"]

[project.urls]
Homepage = "https://github.com/lignum-vitae/goombay"
Issues = "https://github.com/lignum-vitae/goombay/issues"

[tool.hatch.build.sources]
goombay = "goombay"

[tool.hatch.build]
include = ["goombay/**/*.py"]

[tool.hatch.build.targets.wheel]
packages = ["goombay"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
